uint8 OP_ESTOP_SET=1
uint8 OP_CLEAR_FAULT=2
uint8 OP_LINE_CONTROL=3
uint8 OP_GET_INFO=4
uint8 operation
bool enable
---
uint8 RESULT_QUEUED=1
uint8 RESULT_APPLIED=2
uint8 RESULT_REJECTED=3
uint8 RESULT_CONDITION_NOT_CLEARED=4
uint8 RESULT_TIMEOUT=5
uint8 RESULT_CANCELLED=6
uint8 status
string message
---
uint8 status
string message
